schema_version = "1.0.0"

id = "tims_composed_col_tools"
version = "1.0.0"
name = "Tims Composed Col Tools"
tagline = "Tims Composed COL Tools"
maintainer = "Tim Richter"
type = "add-on"
blender_version_min = "4.4.0"

license = [
  "SPDX:GPL-3.0-or-later",
]