[repository]
name = "TimsAddons"
author = "Tim Richter"
description = "Collection of Tim's custom Blender addons"
version = "1.0.0"
blender_version_min = "4.0.0"
blender_version_max = "*"

[[addons]]
module = "TimsBetterExporter"

[[addons]]
module = "OrientedBoundingBox"

[[addons]]
module = "ComposedColTools"