schema_version = "1.0.0"

id = "tims_better_exporter"
version = "1.0.0"
name = "Tims Better Exporter"
tagline = "Tims Better Exporter"
maintainer = "Tim Richter"
type = "add-on"
blender_version_min = "4.4.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
