schema_version = "1.0.0"

id = "tims_better_exporter"
version = "1.0.0"
name = "Tim's Better Exporter"
tagline = "Enhanced export tools for Blender"
maintainer = "Tim Richter"
type = "add-on"
blender_version_min = "4.4.0"